### ISSUE TITLE
amp-Ordinate function using Aitchison distance 

### ISSUE THREAD

**Issue by Hesham999666** [KasperSkytte/ampvis2#110]
Hi,
 
I was interested in making  PCoA ordination plot using Atichison distance measure and amp_ordinate() , However atichison distance was not included in  amp_ordinate() function. 
Usually I do the ordination with Bray-Cruits  distance measure but reviewer advise to use Atichison distance measure  based on 
                                                      **https://pubmed.ncbi.nlm.nih.gov/30801021/** 

Is there is solution for these so I will use  Atichison distance in amp-ordinate () function 

Hesham

**Comment by KasperSkytte** [comment]
Hi Hesham

Aitchison distance is not directly included in `amp_ordinate()`, but there are alternative ways to do it. I have not tried the Aitchison distance before, but it definitely sounds well suited for amplicon data, as it's inherently compositional. You will have to generate a distance matrix elsewhere using fx https://github.com/biocore/DEICODE and then import it to `amp_ordinate()` using the method described here [here](https://madsalbertsen.github.io/ampvis2/articles/faq.html#custom-distance-matrix-for-use-in-ordination). If you want to keep everything together in one markdown for reproducibility, you can always run python code in R through the [reticulate](https://rstudio.github.io/reticulate/) package. Then you can just convert the distance matrix as a data frame and pass it on directly to `amp_ordinate()`.

**Comment by KasperSkytte** [comment]
The distance matrix or data frame must be of class `dist`
