### ISSUE TITLE
Metadata column named "Group" cause problems with amp_heatmap

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/ampvis2#111]
Hi

I have discovered that when one of the metadata columns are named Group it can cause problems with amp_heatmap when grouping samples. It appears that "Group" is a reserved variable name within the function.

The error:
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

Code to reproduce the problem:

`
```{r}
library(ampvis2)
data("MiDAS")
MiDAS$metadata$Group<-MiDAS$metadata$Plant
MiDASsubset <- amp_subset_samples(MiDAS, Plant %in% c("Aalborg West", "Aalborg East") & !SampleID %in% c("16SAMP-749"), minreads = 10000)
```

Grouping by 1 variable work great

```{r}
amp_heatmap(MiDASsubset, group_by = "Plant")
```

Grouping by two variables work great

```{r}
amp_heatmap(MiDASsubset, group_by = c("Period","Plant"))
```
Grouping by two variables work great unless the variable has the name Group (apparently that is reserved within the heatmap function)

```{r}
amp_heatmap(MiDASsubset, group_by = c("Period","Group"))
````

**Comment by KasperSkytte** [comment]
Hi

Sorry for the late response. The issue should now be fixed. I simply renamed `Group` to `.Group` in all relevant functions. It's also a thing in other functions.
