### ISSUE TITLE
facet_by triggers group_by to use the same variable

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/ampvis2#112]
Hi

I have found that facet_by triggers group_by. I guess this is not intended. As the default should be NULL (show all samples)?

Code to reproduce the problem:

`
```{r}
library(ampvis2)
data("MiDAS")
MiDAS$metadata$Group<-MiDAS$metadata$Plant
MiDASsubset <- amp_subset_samples(MiDAS, Plant %in% c("Aalborg West") & !SampleID %in% c("16SAMP-749"), minreads = 10000)
```

PLotting the heatmap shows many samples for this dataset

```{r}
amp_heatmap(MiDASsubset)
```

Facet_by apparently triggers group by and returns only one column in the heatmap

```{r}
amp_heatmap(MiDASsubset, facet_by = c("Plant"))
```

Facet_by in combination with group_by can bring the columns back. 

```{r}
amp_heatmap(MiDASsubset, facet_by = c("Plant"),group_by = "SampleID")
````

**Comment by elpape** [comment]
Noticed the same!

**Comment by KasperSkytte** [comment]
Hi

Sorry for my late response. It should now be fixed, the facets will show all samples in the particular group, and not be aggregated.
