### ISSUE TITLE
Cannot load the tree correctly

### ISSUE THREAD

**Issue by Lei0509** [KasperSkytte/ampvis2#114]
Hi Kasper,

I cannot load my tree correctly using the following code:
**d <- amp_load(otutable = myasvtable,metadata = mymetadata,taxonomy = mytaxonomy,pruneSingletons = FALSE,
tree = ape::read.tree("rootedtree.tree")) # read tree file**

The error message is :
Warning message:
**In ape::drop.tip(phy = tree, tip = tree$tip.label[!tree$tip.label %in% :
drop all tips of the tree: returning NULL**

When I run the code     **ape::read.tree("rootedtree.tree")**  . It return: 

**Phylogenetic tree with 3538 tips and 3531 internal nodes.
Tip labels:
  ae9fc5b50c57fb3773441edcef2f41b9, 076aa58034395275db0c802ffba3e75b, 6d98b5f71e38c20e6d061f8adbb55ea0, c106d7eda7af2b8c1c169dd1276284d7, 1c2078a5c4ee47a7575f11a3a40f37c1, 96acd73109395813e7a59335303f7188, ...
Node labels:
  root, 1.000, 0.487, 0.969, , 0.995, ...

Rooted; includes branch lengths.**

Can you please help me to solve this issue?

Thank you so much for your help!

Best Regards,
Lei

**Comment by KasperSkytte** [comment]
Hi there. To me it seems like you have loaded mismatching data. The tip labels of the tree don't match the names of the OTU's in the otutable. Check that first, and I'll gladly take a deeper look.
