### ISSUE TITLE
Heatmap function creates multiple overlapped heatmap tiles

### ISSUE THREAD

**Issue by msdueholm** [KasperSkytte/ampvis2#119]
There seems to be a bug in the heatmap function that creates multiple heatmaps on top of each other. This is problematic for subsequent image processing in vector-based programs such as Illustrator and Inkscape. 

The problem occurs when the "group_by" option is used. The number of heatmap tiles on top of each other is dependent on the grouping factor and match the number of samples merged by it.

I have also tried to use "Cairo_pdf" for the export, but the same problem occurs.

**Comment by KasperSkytte** [comment]
Not possible to fix, unfortunately, closing.
