### ISSUE TITLE
constrained PCA/RDA

### ISSUE THREAD

**Issue by nielsenmaja** [KasperSkytte/ampvis2#12]
Hi 

I went for using constrained PCA (RDA) the other day, but it did not succeed that well.
I wanted to ask if you can make an example using this function. I want the constrained parameter to be present at the plot and 'colorgradient' similar in several of the examples in ampvis. 

Also, is there a way to add a spell-check to the codes. So that, if any of the commands are spelled wrong, an alarm is given and running the codes is not possible/stopped.

In addition to this, I have experienced that some functions did not run using the XXX_XXX, but only XXX.XXX (using dot instead of underscores). But as far as I can see the functions in ampvis2 are using _.

**Comment by KasperSkytte** [comment]
Hi!

Please show the commands which produced the error and of course the error(s), then it will be much easier to guide you. I'm not sure I understand you correctly, but it is not possible to plot color gradients based on a variable on an ordination plot, the points can only be colored by a discontinuous/categorical variable. But if you want to show how a categorical or numerical variable can explain the observed differences, use the envfit arguments to plot arrows. 

By nature, R is picky, so if you don't type the commands correctly, it will stop with a warning message. So if it runs, you typed it correctly. 

And all arguments have "_" not "." in ampvis2, so maybe you have loaded the 'old' ampvis, not ampvis2?

**Comment by KasperSkytte** [comment]
And have a look here https://madsalbertsen.github.io/ampvis2/reference/amp_ordinate.html#examples
