### ISSUE TITLE
Getting started to include the installation instructions.

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/ampvis2#125]
The getting started page  (https://madsalbertsen.github.io/ampvis2/articles/ampvis2.html) should probably include the installation section. Have heard people look for it in this page.

**Comment by KasperSkytte** [comment]
Thanks. It needs an update in general, I'll see to it soon. How to load the data is also much more flexible now. Throw anything at it.

**Comment by KasperSkytte** [comment]
Updated in a3ee12e7a6e73bec53e404725edf429af72cd5d5
