### ISSUE TITLE
ampvis2 warns about new version available

### ISSUE THREAD

**Issue by bernt-matthias** [KasperSkytte/ampvis2#135]
even if the newest is installed. The warning is: 
`This is ampvis2 version 2.7.12 (newer version 2.7.13 available).`

**Comment by KasperSkytte** [comment]
The version check is done on the main branch, not the releases. Perhaps that's why, no error here. Will work on getting `ampvis2` on CRAN or bioconductor some time this year, then it will check there, or maybe just get removed.
