### ISSUE TITLE
ordinate: NMDS with unifrac

### ISSUE THREAD

**Issue by bernt-matthias** [KasperSkytte/ampvis2#138]
I tried to ordinate with NMDS and unifrac and got the following error:

```
Error in eigen(delta1) : infinite or missing values in 'x'
Calls: amp_ordinate -> <Anonymous> -> eigen
```

this was done using an artificial dataset. So maybe I did something wrong. Is there somewhere a small test data set?

**Comment by KasperSkytte** [comment]
try `AalborgWWTPs`

**Comment by bernt-matthias** [comment]
Works with this dataset. Also thanks for this hint, I will use this dataset for generating test data for the Galaxy tool wrappers (which I'm currently trying to create).
