### ISSUE TITLE
ampvis2.object with dada2 outputs

### ISSUE THREAD

**Issue by marasodi** [KasperSkytte/ampvis2#147]
Dear Kasper
I am using the package and when I try to create the ampvsi2 object I get an error. However I was able to create the phyloseq object with the the same outputs.
Please see below the code and the error
my.ampvis2.object <- amp_load(seqtab.nochim1, taxonomy=taxa2)
Error: No OTU's match between otutable and taxonomy

Thanks in advance.

**Comment by KasperSkytte** [comment]
Hi there. I need a reproducible example with a subset of your data to be able to help.

**Comment by marasodi** [comment]
Dear Kasper 

Thank you for your willingness to assist. I  have attached the example
files. 

Kind regards, 

Kedi 

On 2022-09-02 12:41, Kasper Skytte Andersen wrote:

> Hi there. I need a reproducible example with a subset of your data to be able to help. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/KasperSkytte/ampvis2/issues/147#issuecomment-1235345360
[2]

**Comment by KasperSkytte** [comment]
Hi again. There are no files attached. You can just drag files into the comments window to attach, or email me if you don't want it public.

**Comment by marasodi** [comment]
Hi Kasper 

Please see the attached files. Thanks

On 2022-09-05 09:04, Kasper Skytte Andersen wrote:

> Hi again. There are no files attached. You can just drag files into the comments window to attach, or email me if you don't want it public. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/KasperSkytte/ampvis2/issues/147#issuecomment-1236614076
[2]

**Comment by marasodi** [comment]
Dear Kasper

Kindly see the attached files for the issue number 147 in relation to
ampvis2


Kind regards,

**Comment by KasperSkytte** [comment]
Still none. Are you replying through email? Use github.com

**Comment by marasodi** [comment]
I have sent via researchgate page. Hope it doesnt cause any
inconveniences.

On 2022-09-05 09:59, Kasper Skytte Andersen wrote:

> Still none. Are you replying through email? Use github.com 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/KasperSkytte/ampvis2/issues/147#issuecomment-1236665056
[2]

**Comment by KasperSkytte** [comment]
You just need to transpose the abundance table. `amp_load` expects rows to be OTU/ASV's and colums the samples. See the [documentation](https://kasperskytte.github.io/ampvis2/reference/amp_load.html).

```
library(ampvis2)
#> Loading required package: ggplot2
seqtab <- readRDS("issues/147/seqtab.rds")
taxa <- readRDS("issues/147/taxa.rds")

rownames(seqtab)[1:3]
#> [1] "Silvab_Elution-Buffer-Control_S34_F_filt.fastq.gz"
#> [2] "Silvab_Mock-Control_S37_F_filt.fastq.gz"          
#> [3] "Silvab_PS-Control_S36_F_filt.fastq.gz"
colnames(seqtab)[1:3]
#> [1] "TGTTCGCTCCCCACGCTTTCGCTCCTCAGCGTCAGTAACGGCCCAGAGACCTGCCTTCGCCATTGGTGTTCTTCCCGATATCTACACATTCCACCGTTACNNNNNNNNNNCGGATCCACCGTTAAGCGATGGACTTTCACACCGGACGCGACGAACCGCCTACGAGCCCTTTACGCCCAATAATTCCGGATAACGCTTGCACCCTACGTA"
#> [2] "TACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGNNNNNNNNNNGTAACGGTGGAATGTGTAGATATCGGGAAGAACACCAATGGCGAAGGCAGGTCTCTGGGCCGTTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACA"
#> [3] "TACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCTGNNNNNNNNNNGTAACGGTGGAATGTGTAGATATCGGGAAGAACACCAATGGCGAAGGCAGGTCTCTGGGCCGTTACTGACGCTGAGGAGCGAAAGCGTGGGGAGCGAACA"

#seems like seqtab must be transposed

d <- amp_load(
  otutable = t(seqtab),
  taxonomy = taxa,
  metadata = NULL
)
#> Warning: Could not find a column named OTU/ASV in otutable, using rownames as
#> OTU ID's
#> Warning: Could not find a column named OTU/ASV in taxonomy, using rownames as
#> OTU ID's
#> Warning: No sample metadata provided, creating dummy metadata.

d
#> ampvis2 object with 3 elements. 
#> Summary of OTU table:
#>      Samples         OTUs  Total#Reads    Min#Reads    Max#Reads Median#Reads 
#>           11         2790       317316           12        99914        18146 
#>    Avg#Reads 
#>     28846.91 
#> 
#> Assigned taxonomy:
#>      Kingdom       Phylum        Class        Order       Family        Genus 
#>    2587(93%) 1398(50.11%) 1316(47.17%) 1259(45.13%) 1182(42.37%)  954(34.19%) 
#>      Species 
#>        0(0%) 
#> 
#> Metadata variables: 2 
#>  SampleID, DummyVariable
```

**Comment by marasodi** [comment]
Hi Kasper, thanks.  I did transpose, however when I construct t the heatmap shows a blank page with bases.

**Comment by marasodi** [comment]
[ampvis2 output.pdf](https://github.com/KasperSkytte/ampvis2/files/9566047/ampvis2.output.pdf)
Hi Kasper

This is the output I got. Kindly note that I only get the problem when using Dada2 and not qiime2.

**Comment by KasperSkytte** [comment]
That's because DADA2 uses the exact sequences as ASV ID's, and they are too long to fit on basically any plot. You can rename or aggregate at a different taxonomic level, though if an ASV is unclassified at the chosen level the ASV ID will be used instead by default (`tax_rename` argument).

**Comment by marasodi** [comment]
Thanks for your assistance in this.

**Comment by marasodi** [comment]
The files are in rds format, could you please send me your email
address?

On 2022-09-05 09:59, Kasper Skytte Andersen wrote:

> Still none. Are you replying through email? Use github.com 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/KasperSkytte/ampvis2/issues/147#issuecomment-1236665056
[2]

**Comment by KasperSkytte** [comment]
We've already resolved this right?

**Comment by marasodi** [comment]
yes, thank you!

On 2022-10-11 09:21, Kasper Skytte Andersen wrote:

> We've already resolved this right? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/KasperSkytte/ampvis2/issues/147#issuecomment-1274203945
[2]
