### ISSUE TITLE
amp_ordinate NMDS # of axes

### ISSUE THREAD

**Issue by uschuette** [KasperSkytte/ampvis2#156]
Can I set the number of axes used for the NMDS analysis in amp_ordinate? If so, how can I plot the other axes? X_axis and y_axis =... works for type = "PCA", but I cannot get it to work for type = "NMDS".
Best wishes and thank you for your help,
Ursel

**Comment by KasperSkytte** [comment]
Hi Ursel

Sorry for the late response, summer vacation times. Fixed in v2.8.1.

**Comment by uschuette** [comment]
Hi Kasper,
No worries at all and thank you for your help!
Best wishes and have a good rest of your summer,
Ursel
