### ISSUE TITLE
R fatal error when drawing heatmaps with more than 2 variables

### ISSUE THREAD

**Issue by courtherms** [KasperSkytte/ampvis2#157]
Hey, we love this package in my lab but I am running into a problem that no one here can understand. 

I have a phyloseq object created from a standard V3-V4 16s rRNA sequencing run. 
Metadata:
![image](https://github.com/KasperSkytte/ampvis2/assets/118815315/e17b34c7-7117-4e50-b830-456a30ebebbe)

When I subsample only 2 of the inoculants (i.e. water and S2H08), then I can draw the heatmap no problem.
```
amp.sub <- amp_subset_samples(amp, Inoculant %in% c("H1F01", "Water"))
amp_heatmap(data= amp.sub, tax_aggregate = "Genus", group_by = "Cultivar", facet_by = "Inoculant")
```

But when I try to visualize the whole dataset:
`amp_heatmap(data= amp, tax_aggregate = "Genus", group_by = "Cultivar", facet_by = "Inoculant")`
Or subsample all three inoculants
`amp.sub <- amp_subset_samples(amp, Inoculant %in% c("H1F01", "Water", "S2H08"))`
And draw the the heatmap:
`amp_heatmap(data= amp.sub, tax_aggregate = "Genus", group_by = "Cultivar", facet_by = "Inoculant")`

R gives me this:
![image](https://github.com/KasperSkytte/ampvis2/assets/118815315/170a29e5-8bf4-4193-a1df-f1378d2c940c)

With no other explanation. Running out of ideas/things to Google to solve this one....

**Comment by KasperSkytte** [comment]
Hello. Check memory usage. Do you max out your memory?

**Comment by courtherms** [comment]
![image](https://github.com/KasperSkytte/ampvis2/assets/118815315/2b59fc62-8b25-4d7d-a5b0-240a9cd9f8dd)
Apparently not!

**Comment by KasperSkytte** [comment]
I mean while running the code, not when idle. If you only have 2GB, you are definitely limited. Monitor task manager if on windows while executing the code.

**Comment by courtherms** [comment]
Start:
![image](https://github.com/KasperSkytte/ampvis2/assets/118815315/3cd48654-0902-482c-9e77-2e269a9e40fb)

It hovers very consistently around 151000-153000 used. When I run the code, that fails, the memory used actually drops to around 147000-149000. 

We have 3 terabyte memory on the server, but I guess maybe R isn't accessing that??

**Comment by KasperSkytte** [comment]
Arh, you're on an HPC, so 3TB memory? Then it's probably not a memory issue. Well, I'm not sure why it crashes. But if it was due to the ampvis2 package it would show an error in the console. I suspect something on the system is blocking R from doing its thing. Are you ressource limited? For example through a scheduler like SLURM etc? Try on a different machine. I can't help much without knowing the actual setup.

**Comment by courtherms** [comment]
Ah, very well.. I will have to talk to our server-guy because I don't know the answer to any of those questions. Thanks for taking a look!

**Comment by KasperSkytte** [comment]
To me it seems like R is killed because it's using too many ressources than allowed. So I would start there. You're welcome
