### ISSUE TITLE
Generating loading/biplot

### ISSUE THREAD

**Issue by susheelbhanu** [KasperSkytte/ampvis2#160]
Hi,

You probably have this, but i couldn't find it in your documentation or you code, but is it possible to generate a `loading` or `biplot` following `amp_ordinate`?

I'm looking for something like the below:
![image](https://github.com/KasperSkytte/ampvis2/assets/9979661/8104a954-244f-40ab-983d-745a7ec4a95d)

My current code looks like so:
```
amp_ordinate(filtered_d,
             type = "pcoa",
             distmeasure = "bray",
             sample_color_by = "Ecosystem",
             sample_shape_by = "Habitat",
             sample_colorframe = TRUE,
             sample_colorframe_label = "Project") 
```

Thank you!

**Comment by KasperSkytte** [comment]
Hi there. Have a look at the `envfit*` arguments https://kasperskytte.github.io/ampvis2/reference/amp_ordinate.html.
