### ISSUE TITLE
amp_boxplot order genera by corresponding phyla

### ISSUE THREAD

**Issue by uschuette** [KasperSkytte/ampvis2#161]
Is there a way in amp_boxplot to order e.g. the genera by corresponding phyla? We found a longer way to do this by extracting the taxa names from amp_heatmap and specifying them as rownames and then using _order_y = levels(fct_rev(as.factor(rownames(amp_df)))_ in amp_boxplot, but maybe there is a faster way?

Thank you for your help!!
Ursel

**Comment by KasperSkytte** [comment]
No, the only way is to order the factor yourself. Also see #162 and #163. Highly recommend updating ampvis2.
