### ISSUE TITLE
How to reorder the Y axis from the default ampvis2 heatmap

### ISSUE THREAD

**Issue by isuvodeep** [KasperSkytte/ampvis2#163]
amp_heatmap(dsubset,
                 #group_by = "Temp",  
                 facet_by = "temp_gradient",  
                 tax_aggregate = "Class",   
                 tax_add = "Phylum",          
                 tax_show = 5,   
                 plot_colorscale = "sqrt",   
                 plot_values = FALSE,        
                 normalise = TRUE) 

I am getting my heatmap for the top 5 taxa from my dataset. I want to reorder the taxa that I am getting by default. Like in my dataset, I am getting (Cyanophyceae, Alphaproteobacteria, Gammaproteobacteria,.......etc. ). Now I would like to reorder gammaproteobacteria in the first position. How can I do that? 

Thank you very much in advance.

**Comment by KasperSkytte** [comment]
Hi. Using `order_y_by`. For example:

``` r
require("ampvis2")
#> Loading required package: ampvis2
#> Loading required package: ggplot2

#example heatmap
heatmap <- amp_heatmap(
  AalborgWWTPs,
  group_by = "Plant",
  tax_show = 5
)
heatmap
```

![](https://i.imgur.com/omgEDqd.png)

``` r

#display and extract taxa from y axis factor
taxa <- heatmap$data$Display
unique(taxa) #also includes those not plotted
#> [1] Actinobacteria Bacteroidetes  Chloroflexi    Firmicutes     Proteobacteria
#> 264 Levels: k__Bacteria_OTU_7088 k__Bacteria_OTU_4041 ... Proteobacteria
taxa <- levels(droplevels(taxa))
taxa
#> [1] "Firmicutes"     "Chloroflexi"    "Bacteroidetes"  "Actinobacteria"
#> [5] "Proteobacteria"

#reorder however you want
taxa_reordered <- taxa[c(1,4,2,3,5)]
taxa_reordered
#> [1] "Firmicutes"     "Actinobacteria" "Chloroflexi"    "Bacteroidetes" 
#> [5] "Proteobacteria"

#generate a new heatmap with the new order
new_heatmap <- amp_heatmap(
  AalborgWWTPs,
  group_by = "Plant",
  tax_show = 5,
  order_y_by = taxa_reordered
)
new_heatmap
```

![](https://i.imgur.com/sugMPLE.png)

<sup>Created on 2023-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
