### ISSUE TITLE
Specify ASV/OTU column by name or index?

### ISSUE THREAD

**Issue by bernt-matthias** [KasperSkytte/ampvis2#166]
I often have count tables that have an empty string in the header that marks the OTU/ASV column. So far I could not find a way to handle this directly and replaced by "ASV" (using `sed`). It would be cool if I could directly specify the name (or index) of the column contains the ASVs. I experimented a bit with `fread`s `key` argument, but without success. 

I could need this for the ampvis2 Galaxy tools over here: https://github.com/galaxyproject/tools-iuc/blob/main/tools/ampvis2/load.xml

**Comment by KasperSkytte** [comment]
I would argue that if a CSV file is missing a column name, it's in an invalid format. But could make it configurable which column contains the OTUs/ASVs, though it might cause trouble downstream, since apples must be called apples.

**Comment by bernt-matthias** [comment]
I just observed that most of the packages (e.g. dada2) seems not to name the OTU/ASV column  which is a problem for automated analyses. So I thought it might be an option to do this internally, e.g. default to the first column if there isn't a column with the name OTU/ASV.

**Comment by KasperSkytte** [comment]
It's a good idea making it optional, I'll take a look
