### ISSUE TITLE
How to plot a dendrogram in ampvis2?

### ISSUE THREAD

**Issue by LingTJ** [KasperSkytte/ampvis2#172]
Hello, dear ampvis2 developers,
I have been using this package for several years, and cited this package in my paper (https://doi.org/10.1021/acs.jafc.2c01005). This is a good package for me.
Now I'm trying to plot a dendrogram using both dissimilarity (Bray) and transform functions (Hellinger) for the PCoA. But I could not find the codes/functions in home page of ampvis2.
Could you pleae tell me how to do this in ampvis2? Thank you.

TJ Ling

Thank you for using ampvis2!

If you encounter a problem with ampvis2 that you are unable to resolve, this is the place for discussing the problem with developers to find a solution. To best help you quickly, please first make sure that:

 - you have the latest version of the package installed
 - you have carefully read the [documentation](https://kasperskytte.github.io/ampvis2/reference/index.html) of the ampvis2 function(s) used
 - you have searched the GitHub issues page or the internet for similar or identical problems

Should the problem still persist, then please provide a *minimal* reproducible example, preferably using [reprex](https://www.tidyverse.org/help/#reprex), with self-contained code so that anyone can copy the code and reproduce the problem to easily start debugging without further communication. 

If you suspect that the data used is involved in causing the trouble, then please upload it (preferably a minimal subset) to [figshare](https://figshare.com/) or similar services and provide a link to it.

**Comment by KasperSkytte** [comment]
Hi there. I have no plans to implement new features for a while, unless people contribute. But I'm not sure what you mean by adding dendrograms to an ordination plot, can you provide an example? But maybe this is equivalent https://rdrr.io/github/jfq3/ggordiplots/man/gg_ordicluster.html

**Comment by LingTJ** [comment]
Hi, Kasper,
Thank you again for your quick reply.
I have addressed the issue by using packages of vegan and factoextra. The key functions are decostand in vegan, which is able to do transform (Hellinger) before Bray-Curtis distance algorithm.
Thank you.
TJ
