### ISSUE TITLE
Installation info needed in description

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/ampvis2#2]
library("devtools")
install_github("MadsAlbertsen/ampvis2")

**Comment by KasperSkytte** [comment]
Also:
install.packages("devtools")
source("http://bioconductor.org/biocLite.R")
biocLite("Biostrings")
biocLite("DESeq2")
biocLite("munsell")
biocLite("stringi")
biocLite("chron")
biocLite("permute")
biocLite("assertthat")
biocLite("tibble")
biocLite("rmarkdown")
biocLite("readxl"

**Comment by MadsAlbertsen** [comment]
You are welcome to update it and submit a pull-request :)

**Comment by KasperSkytte** [comment]
Close it. In the future it will simply be:
source("http://bioconductor.org/biocLite.R")
biocLite("MadsAlbertsen/ampvis2")
