### ISSUE TITLE
amp_subset_samples prints message that is shown in rmarkdown

### ISSUE THREAD

**Issue by SorenKarst** [KasperSkytte/ampvis2#23]
amp_subset_samples prints message with subsampling statistics. Useful for analysis but annoying when reporting in Rmarkdown, where extra effort has to be made to remove it. Can message be printed with warning/message status or similar, so it can be turned off with message=FALSE or warning=FALSE in Rmarkdown.

**Comment by KasperSkytte** [comment]
Fixed in 74662aa311996ce6a179e563ab0899accbe978f9
