### ISSUE TITLE
amp_alphadiv scrambles the reported data

### ISSUE THREAD

**Issue by MadsAlbertsen** [KasperSkytte/ampvis2#27]
Currently the data$metadata and data$abund is not sorted in the same order. Hence, the following 2 lines of code scrambles the number of reads reported per sample (and the other measures I guess).

```
results <- data$metadata
results$Reads <- colSums(data$abund)
```

If possible, then always use merge/join instead. It's too risky to assume that order is preserved across data frames.

**Comment by KasperSkytte** [comment]
Fixed in 6b97a4549c2dfb4a4b86b0edba55d8b35a804ca5
