### ISSUE TITLE
amp_load dummy data bug

### ISSUE THREAD

**Issue by SorenKarst** [KasperSkytte/ampvis2#31]
amp_load object structure wrong if no metadata is provided.
```

# Test code
library(ampvis2)
library(tidyverse)

otutable <- read_delim("textmap_test_otutable.txt", delim = ",")

d <- amp_load(otutable)

amp_heatmap(d)
```

[textmap_test_otutable.txt](https://github.com/MadsAlbertsen/ampvis2/files/1528717/textmap_test_otutable.txt)

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/MadsAlbertsen/ampvis2/commit/554a680f14455192669ce9ae2008ab512f8dce2d
