### ISSUE TITLE
# Export otutable with one sample bug

### ISSUE THREAD

**Issue by SorenKarst** [KasperSkytte/ampvis2#32]
amp_export_otutable returns an error if attempting to export otutable with one sample.
[textmap_test_otutable.txt](https://github.com/MadsAlbertsen/ampvis2/files/1528723/textmap_test_otutable.txt)

```
# Test code
library(ampvis2)
library(tidyverse)

otutable <- read_delim("textmap_test_otutable.txt", delim = ",")
metadata <- data.frame(SeqID = "MQ170823-258", Var1 = "test")

d <- amp_load(otutable, metadata)

amp_heatmap(d)

amp_export_otutable(d, "test_otutable.txt")
```

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/MadsAlbertsen/ampvis2/commit/169fd8fddeb4f58e574d115a74fe401e8be59f1f
