### ISSUE TITLE
Ordination plots without samples.

### ISSUE THREAD

**Issue by grabear** [KasperSkytte/ampvis2#36]
I'm having trouble getting an ordination plot without samples.  All I want is the OTU ordination plot as in [phyloseq](https://joey711.github.io/phyloseq/plot_ordination-examples.html#(1)_just_otus).

**Comment by KasperSkytte** [comment]
Hi @grabear 

Thank you for pointing it out, we may consider implementing that. It will probably not be in the near future though, so for now I can just show you how to do it manually:

```R
library(ampvis2)
library(tidyverse)

d <- amp_subset_taxa(AalborgWWTPs, 
                     c("p__Actinobacteria",
                       "p__Bacteroidetes", 
                       "p__Cyanobacteria",
                       "p__Firmicutes", 
                       "p__Proteobacteria"))
res <- amp_ordinate(d,
                    type = "CA",
                    transform = "hellinger",
                    detailed_output = TRUE)
ggplot(res$dspecies, aes_string(x = "CA1",
                                y = "CA2", 
                                color = "Phylum")) +
  geom_point() +
  theme_classic()

```

**Comment by grabear** [comment]
Ok!  Thanks I might work on that if you're not opposed to it? @KasperSkytte

**Comment by KasperSkytte** [comment]
Sure, give it a go! :)

**Comment by KasperSkytte** [comment]
@grabear I know this is from February, but did you give it a go? If so then there is no reason to spend time that has already been spent implementing it :)
