### ISSUE TITLE
Bray-curtis similarity plot

### ISSUE THREAD

**Issue by jakobbrandt** [KasperSkytte/ampvis2#37]
Viste dig det der lækre Bray-curtis similarity plot. Kunne være lækkert som en ekstra-funktion til amp_ordinate.

**Comment by KasperSkytte** [comment]
Available in [ampvis2extras](https://kasperskytte.github.io/ampvis2extras/reference/amp_betadiv.html) for now

**Comment by jakobbrandt** [comment]
Tror der er en bug med **label_by** delen af **amp_betadiv** funktionen. Samples bliver plottet i random order... i hvert fald med mit data.
