### ISSUE TITLE
Different most abundant taxa in amp_heatmap and amp_boxplot using tax_show=N

### ISSUE THREAD

**Issue by VGalata** [KasperSkytte/ampvis2#38]
I am not sure whether this is a bug but I get different sets of taxa using `amp_heatmap` and `amp_boxplot`. 
The parameter `tax_show` is set to 10 in both cases and the functions are called in the same manner (see below). As I understood from the provided examples the top `N` most abundant taxa should be plotted if `tax_show` is not set to `"all"`. If this is correct it would be good to know what affects the selection of the top `N` taxa in both functions.

Thank you in advance!

Used version: `ampvis2_2.3.2`

Code snippet:

```R
ampvis2_obj_no_contam <- ...
p_ampvis_rank         <- "Phylum"
p_ampvis_tax_add      <- NULL
p_ampvis_tax_show     <- 10

amp_heatmap(
  data=ampvis2_obj_no_contam,
  group_by=sample_group,
  tax_aggregate=p_ampvis_rank,
  tax_add=p_ampvis_tax_add,
  tax_empty="OTU",
  tax_show=p_ampvis_tax_show
)

amp_boxplot(
  data=ampvis2_obj_no_contam,
  group_by=sample_group,
  tax_aggregate=p_ampvis_rank,
  tax_add= p_ampvistax_add,
  tax_empty="OTU",
  tax_show=p_ampvis_tax_show
)
```

Screenshots:
![ampvis2_issue_bp_top10](https://user-images.githubusercontent.com/5700085/36838757-580ecd20-1d40-11e8-8736-941a0a97de56.png)
![ampvis2_issue_hm_top10](https://user-images.githubusercontent.com/5700085/36838758-583691f2-1d40-11e8-8e45-3a46ebac75dc.png)

**Comment by KasperSkytte** [comment]
Hi @VGalata!

Thank you for pointing it out, but it's just because `amp_boxplot` by default orders by median while `amp_heatmap` orders by mean. It makes more sense to order by median in boxplots in my opinion. So setting the `sort_by` to the same in both plots hopefully gives you the same result. If not, please let me know, then something is totally wrong :)

**Comment by VGalata** [comment]
Dear @KasperSkytte,

I knew I missed something. ^^ Yes, using the same value for `measure`/`sort_by` resolved the issue.

Thank you for the fast reply!

**Comment by KasperSkytte** [comment]
Great! No problem, glad you weren't silent with it :+1:

**Comment by caonetto** [comment]
Hi @KasperSkytte ,
This issue seems to be still persisting, I have tried a boxplot sorted by mean and a heatmap and the order and taxa displayed are not the same. Any idea?

Cheers,
