### ISSUE TITLE
RDA and CCA plots with 2 values on x and y axis

### ISSUE THREAD

**Issue by suzanakraus** [KasperSkytte/ampvis2#40]
Hi there! I plotted my sequencing data and metadata using ampvis in RStudio and I got 2 values on both x and y axis for my RDA and CCA graphs, and I'm not really sure how to interpret them. 
I used the command amp_ordinate to prepare the graph. 
RDA graph was: x axis =  [10%/60/2%] and y axis = [6.2%/ 37.3%]
CCA graph was: x xis = [ 8.4% /  67.1] and y axis was = [3.6% / 28.9%]

Can someone help clarifying please?
Thank you!!

**Comment by KasperSkytte** [comment]
Hi!

Thank you for using ampvis2. I see I forgot to elaborate on these percentages in the documentation, I will update it soon. The first value is the eigenvalue of the particular axis divided by the sum of all UNconstrained eigenvalues, and the second is the eigenvalue of the axis divided by the sum of all constrained eigenvalues. So think of it like the first value is an expression of the axis contribution to the UNconstrained space and the second to the constrained space. Most other software tools only show the first or none at all.

**Comment by suzanakraus** [comment]
Thank you!
