### ISSUE TITLE
amp_venn issue

### ISSUE THREAD

**Issue by caonetto** [KasperSkytte/ampvis2#42]
Hi, I am trying to run amp_venn on a dataset but I get the following error,

amp_venn(d, cut_a = 10, group_by = "Winery")
Error in amp_venn(d, cut_a = 10, group_by = "Winery") : 
  object 'p' not found

Any ideas?

Thanks,

Cris

**Comment by KasperSkytte** [comment]
Hi!

`amp_venn` only supports a maximum of 3 different groups. But the `group_by` variable is checked in the function, so you should have gotten an error stating this. I will look into it shortly.

**Comment by caonetto** [comment]
Ok,
Thanks again.
