### ISSUE TITLE
CCA analyses

### ISSUE THREAD

**Issue by caonetto** [KasperSkytte/ampvis2#43]
Hi, I am trying to run a CCA but I get the following error, Error in cca.default(inputmatrix, ...) : 
  all row sums must be >0 in the community data matrix.
```
amp_ordinate(d,
             type = "CCA",
             transform = "Hellinger",
             sample_color_by = "Cellar_location", sample_plotly = "all", filter_species = 10, species_plot = TRUE, species_nlabels = 15, species_shape = 20,
species_rescale = TRUE)
```

I have previously filtered the data using the ampvis_subset sample which as indicated automatically removes absent OTUs?, however I still get this error.

Thanks for your help.

**Comment by KasperSkytte** [comment]
What version of ampvis2 have you installed?

**Comment by caonetto** [comment]
Hi Kasper,
Thanks for your quick reponse.
I am running ampvis2 version 2.3.6.

Any ideas?

Cheers,

**Comment by KasperSkytte** [comment]
Hi

If you've used CCA you should have gotten an error saying you haven't supplied a `constrain` variable, which you didn't in the code you provided, so are you sure that code produced the error? Can you please provide a minimal reproducible example (see [reprex](https://www.tidyverse.org/help/#reprex)) of the problem, perhaps with a minimal subset of your data?

**Comment by caonetto** [comment]
Hi Kasper,
Sorry I pasted the wrong command, but the error is the actual one,
```
amp_ordinate(d2,
              type = "CCA",
              transform = "Hellinger",
              constrain = c("Time_point"),
              sample_color_by = "Time_point",
              sample_plotly = "all", filter_species = 0.1, species_plot = TRUE, species_nlabels = 10, species_shape = 20,
 species_rescale = TRUE, species_label_color = "Black")
Error in cca.default(d$X, d$Y, d$Z) : 
  all row sums must be >0 in the community data matrix
```
Thanks for your reply, I am trying to get a reproduction with repex  but I am not familiar with the package.

**Comment by KasperSkytte** [comment]
Hi again

`reprex` just makes sure that the code you use is self-contained and can be easily run on any machine to reproduce the error, which is needed to debug the error. I need the whole story, so *all* relevant code you've run, and perhaps a small subset of the data.
You said you've used `amp_subset_samples`, however I don't see it in the code you wrote. So maybe the subset resulted in empty data? I have never seen the error before, but it's produced by the `cca` function from `vegan` which performs the backend calculations for the ordination, and it seems like it gets empty data or all OTU's have 0 reads in the subset. Does the subsetted data show anything in other `ampvis2` visualisation function like `amp_heatmap`?

**Comment by caonetto** [comment]
Hi Kasper,
I did not include the amp_subset_samples before but for creating d2 I used,
```
d2 <- amp_subset_samples(d,
                                    Time_point %in% c("T1"))
395 samples and 346 OTUs have been filtered 
Before: 529 samples and 1821 OTUs
After: 134 samples and 1475 OTUs
```
The amp_subset_samples is removing empty OTUs in all samples by default right? 
All other functions work ok, like heatmaps and RDAs, PCAs etc, the problem is only when I try to do a CCA or CA.

Thanks again for your help.

**Comment by caonetto** [comment]
Hi Kasper,
Problem solved, one of the samples by some reason had 0 counts in all OTUs, and amp_subset_samples was not dealing with this issue.

Cheers,

Cris.

**Comment by KasperSkytte** [comment]
Hi again!

The error is coming from the `vegan` function `cca.default` which performs the actual CCA ordination calculations. It doesn't make sense to include samples with no information in the CCA analysis, so that's why it complains. `amp_subset_samples` only filters samples, not the abundances, so it is not caused by that, it's apparantly just due to your data set. That's why I was asking for a minimal, and self-contained reproducible example so the error can be reproduced and debugged. Often this makes people realise what they actually did, which is essential for debugging.

To generate a `reprex` you simply run for example:
```r
reprex::reprex({
  #your code here#
})
```

The result is then rendered in the viewer, which you then copy and paste here. The result could for example be:
```r
library(ampvis2)
#> Loading required package: ggplot2
# load my data (could be loaded from a dropbox shared folder, figshare file,
# or other..., and directly loaded by readRDS(url('url'))) but now just
# preloaded example data in ampvis2:
d <- amp_load(otutable = ampvis2::example_otutable, metadata = ampvis2::example_metadata)
d$abund[, "16SAMP_3893"] <- 0  #set all OTUs in one sample to 0
amp_ordinate(d, type = "ca")
#> Error in cca.default(inputmatrix, ...): all row sums must be >0 in the community data matrix
```

But I had overestimated the complexity of the error message, it's fortunately rather simple :)

Thanks for reporting the error!
