### ISSUE TITLE
amp_alphadiv reports rarefied read counts. Should be raw.

### ISSUE THREAD

**Issue by MadsAlbertsen** [KasperSkytte/ampvis2#45]
amp_alphadiv reports rarefied readcounts. I think it would make sense to still include the raw number of reads. Maybe as "RawReads" - or simply just report reads as "RawReads" as far as I remember this is also how it used to behave.

**Comment by KasperSkytte** [comment]
Fixed in d60b4bd1757328fcee47e7a30aa5012b6f84b454
