### ISSUE TITLE
amp_timeseries default y-axis to ylim(0,NA)

### ISSUE THREAD

**Issue by MadsAlbertsen** [KasperSkytte/ampvis2#47]
I noticed that the defult settings in timeseries simply scales the abundance relative to min and max of the data. In most cases it would be better to start the y-axis at 0. E.g. default could be ylim(0,NA)? Or something similar instead?

**Comment by KasperSkytte** [comment]
Could you provide an example? I tried different data and always get from 0 and up on the y-axis.
