### ISSUE TITLE
Bug in  amp_subset_samples()

### ISSUE THREAD

**Issue by aaronsaunders** [KasperSkytte/ampvis2#51]
I think a bug may have been introduced in  amp_subset_samples(). 

I cannot get it to recognize the metadata colnames. This is the same for my data and with the MiDAS dataset in the package. 

```
data("MiDAS")
MiDASsubset <- amp_subset_samples(MiDAS, Plant %in% c("Aalborg West", "Aalborg East"))
```

> Error in Plant %in% c("Aalborg West", "Aalborg East"): object 'Plant' not found
> Traceback:
> 
> 1. amp_subset_samples(MiDAS, Plant %in% c("Aalborg West", "Aalborg East"))
> 2. Plant %in% c("Aalborg West", "Aalborg East")

It is the correct variable name.

`MiDAS$metadata %>% colnames()`
>     'SampleID'
>     'Plant'
>     'Date'
>     'Year'
>     'Period'

`packageVersion("ampvis2")`

[1] ‘2.3.18’

`version`
> platform       x86_64-conda_cos6-linux-gnu 
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          5.0                         
> year           2018                        
> month          04                          
> day            23                          
> svn rev        74626                       
> language       R                           
> version.string R version 3.5.0 (2018-04-23)
> nickname       Joy in Playing

**Comment by KasperSkytte** [comment]
Hej Aaron!

Thank you for bringing this to our attention. I know about the error, it was introduced with the last few commits somewhere, but I have both had holidays and paternity leave, so I haven't had time to have a look at it before now. I will come up with a solution today or tomorrow.

- Kasper

**Comment by KasperSkytte** [comment]
In the meantime you can try an older version, for example the latest stable release `2.3.11` (not the latest bleeding edge development version). You can install it with `devtools::install_github("madsalbertsen/ampvis2@2.3.11")`

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/MadsAlbertsen/ampvis2/commit/8a381afb5ab3dceeae741fc852233f71aed644e6

**Comment by aaronsaunders** [comment]
Legend. Now running fine on my code too.

Thanks for fixing it. This is a very useful software and I am sure I am not the only one that is grateful for the work you and Mads have put into this.

Cheers. Aaron
