### ISSUE TITLE
Error using RStudio for ordination in shiny package

### ISSUE THREAD

**Issue by ghost** [KasperSkytte/ampvis2#53]
All features in the ampVis2 Shiny package work great from my RStudio environment with the exception of ordination.  Could you point me in the right direction for my error message: **Error in %in%: cannot open file '~/R/x86_64-pc-linux-gnu-library/3.4/plotly/R/sysdata.rdb': No such file or directory**  when I try to use ordination.  

shiny::runGitHub("amplicon-visualiser","Kasperskytte")
Error in %in%: cannot open file '~/R/x86_64-pc-linux-gnu-library/3.4/plotly/R/sysdata.rdb': No such file or directory
  90: %in%
  89: FUN
  88: vapply
  87: has_attr
  86: FUN
  85: lapply
  84: supply_defaults
  83: plotly_build.plotly
  81: createPayload
  80: origRenderFunc
  79: output$ord
   3: runApp
   2: runUrl
   1: shiny::runGitHub

**Comment by KasperSkytte** [comment]
Hi

I have never seen that error before. But maybe try reinstalling `plotly` (with `install.packages("plotly")`)? 
If that doesn't work, try installing the development version of both `plotly` (with `devtools::install_github("ropensci/plotly")`) and `ggplot2` (with `devtools::install_github("tidyverse/ggplot2")`). I run Linux as well, everything is fine.
