### ISSUE TITLE
Axis title when using amp_boxplot with "normalise = FALSE"

### ISSUE THREAD

**Issue by Cloacina** [KasperSkytte/ampvis2#54]
Hi,

When I use amp_boxplot with "normalise = FALSE", the x-axis is the reads number instead of the relative abundance. However, the x-axis title is still "Read Abundance (%)". Could you help to fix it?

Thank you!

**Comment by KasperSkytte** [comment]
Hi

Thank you for noticing. I've made a fix, just reinstall `ampvis2` as described on the website.

**Comment by KasperSkytte** [comment]
By the way, you can always use `+ ylab("")` or `+xlab("")` on the plot to adjust it yourself, see https://ggplot2.tidyverse.org/reference/labs.html
