### ISSUE TITLE
load tree file by amp_load function

### ISSUE THREAD

**Issue by LingTJ** [KasperSkytte/ampvis2#55]
Dear ampvis2 guys,
Thank you so much for developing the wonderful R package.
My question is how to load tree file by amp_load function.
I can see the codes for loading otutable, metadata, and fasta at the link (https://madsalbertsen.github.io/ampvis2/reference/amp_load.html),  but no one for tree file.

Would you please give a code for load tree file in amp_load? Thanks a lot.

**Comment by KasperSkytte** [comment]
Hi @LingTJ 

You need to provide the tree as an object of class `phylo` which is done by `ape::read.tree()`, eg:

```r
d <- amp_load(otutable = read.csv("path/to/otutable.csv", check.names = FALSE), 
              metadata = read.csv("path/to/metadata.csv", check.names = FALSE),
              tree = ape::read.tree("path/to/tree.tre")
              )
```

The reason why you have to load it manually with the `ape` function is because the format and options for loading the tree often varies (see [the docs](https://www.rdocumentation.org/packages/ape/versions/5.1/topics/read.tree)), hence we did not include it in the `amp_load()` function. Bear in mind that the only thing the tree is used for at the moment is for calculating Generalized UniFrac distances for ordination and must be rooted, and is therefore not needed for everything else.

**Comment by LingTJ** [comment]
Dear Kasper,
Thank you so much for the answer. I can load the tree file now.
May I ask an other question? For microbial community analysis, do you prefer a PCoA with distmeasure of "wunifrac" or of "bray"?

**Comment by KasperSkytte** [comment]
Hi again!

It always depends on your research question. Usually Bray-Curtis (also the most used) is fine for ecological data. UniFrac incorporates phylogeny, which is sometimes better when comparing environments where the species are highly related, but as there are many ways to calculate the phylogenetic tree and to root the tree, it is in my opinion too unreliable and uncomparable between studies. UniFrac generally also requires similar sequencing depths of the all the samples compared. 
Unless you are interested in the details of the difference of individual species or samples, my advice is to try out a few distance measure and see if they reveal somewhat the same overall patterns, and if so then it doesn't matter much which measure you choose. 

A few key references (there are many):
https://www.elsevier.com/books/numerical-ecology/legendre/978-0-444-53868-0 (master book with all the details)
https://link.springer.com/article/10.1007/s004420100716 (also Legendre)
https://doi.org/10.1111/j.1574-6941.2007.00375.x and https://sites.google.com/site/mb3gustame/  (overview of ordination and multivariate analyses for ecological data) 
https://www.umass.edu/landeco/teaching/multivariate/readings/McCune.and.Grace.2002.chapter6.pdf (distance measures)

**Comment by LingTJ** [comment]
Thank you Kasper. This is the best answer I ever received from GitHub.

**Comment by LingTJ** [comment]
Dear Kasper,
I have successively plotted the PCoA with wunifrac distmeasure following the codes at https://madsalbertsen.github.io/ampvis2/reference/amp_ordinate.html.
I'm wondering if you could kindly provide my some codes to export the pcoa coordinates (at least PCo1 and PCo2) for every sample from the PCoA plot?

Thank you very much.
TJ

**Comment by KasperSkytte** [comment]
Hi TJ

You can just set `detailed_output = TRUE`, and then the site/sample scores will be available in `$dsites` combined with the metadata, for example:

```r
library(ampvis2)
#> Loading required package: ggplot2
test <- amp_ordinate(AalborgWWTPs,
  type = "pcoa",
  distmeasure = "bray",
  transform = "none",
  detailed_output = TRUE
)
#> Calculating distance matrix...
#> Done.
head(test$dsites[, c("PCo1", "PCo2")])
#>                     PCo1        PCo2
#> 16SAMP-747    0.01186119  0.22570349
#> 16S-AMP-1168 -0.09816825 -0.20143016
#> 16SAMP-4603   0.30430119 -0.09546843
#> 16S-AMP-1149  0.24025217  0.03777322
#> 16SAMP-537   -0.19136858 -0.06066154
#> 16S-AMP-1114 -0.17767635 -0.09910849
```

**Comment by LingTJ** [comment]
Hi, Kasper,
It's done. Thank you for the kind help!

TJ

**Comment by Lei0509** [comment]
Hi Kasper, 

I cannot load my tree correctly using the following code: 
d <- amp_load(otutable = myasvtable,metadata = mymetadata,taxonomy = mytaxonomy,pruneSingletons = FALSE,
              tree = ape::read.tree("rootedtree.tree"))     # read tree file

The error message is :
Warning message:
In ape::drop.tip(phy = tree, tip = tree$tip.label[!tree$tip.label %in%  :
  drop all tips of the tree: returning NULL

Can you please help me to solve this issue?

Thank you so much for your help!

Best Regards, 
Lei
