### ISSUE TITLE
Multiple envfit arrows in one plot.

### ISSUE THREAD

**Issue by caonetto** [KasperSkytte/ampvis2#56]
Hi Kasper,
I was wondering if its possible to fit multiple envfit arrows in one plot like it can be done in vegan.

Thanks,

Cris.

**Comment by KasperSkytte** [comment]
Hi Cris!

Of course, you just supply a vector with the variables that you want to fit, fx `amp_ordinate(AalborgWWTPs, envfit_factor = c("Year", "Period"))` 

 - Kasper
