### ISSUE TITLE
error when loading phyloseq object with ASVs

### ISSUE THREAD

**Issue by camillaln** [KasperSkytte/ampvis2#59]
Hi, 

I am trying to import a phyloseq object of ASVs made with DADA2.
I have renamed the ASVs ASV1, ASV2.... 
```
> nq1F515R806psF
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1890 taxa and 28 samples ]
sample_data() Sample Data:       [ 28 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 1890 taxa by 7 taxonomic ranks ]
```
I used you recipe for importing phyloseq objects, but get an error.
Here are my commands:
```
> obj <- nq1F515R806psF
> otutable <- data.frame(
    OTU = rownames(phyloseq::otu_table(obj)@.Data),
    phyloseq::otu_table(obj)@.Data,
    phyloseq::tax_table(obj)@.Data,
    check.names = FALSE
  )
Error in data.frame(OTU = rownames(phyloseq::otu_table(obj)@.Data), phyloseq::otu_table(obj)@.Data,  : 
  arguments imply differing number of rows: 28, 1890
```
Could you help me figure out what I am doing wrong? 

Thanks,
Camilla

**Comment by KasperSkytte** [comment]
Hi Camilla!

I think you maybe encounter this because the rows of your `tax_table` are not the same as the rows of your `otu_table`. You use the [`phyloseq::taxa_are_rows()`](https://rdrr.io/bioc/phyloseq/man/taxa_are_rows-methods.html) function (and `taxa_are_rows = TRUE/FALSE` argument to `phyloseq::otu_table()`) to make sure rows are OTU's (in your case ASV's).

Kasper

**Comment by camillaln** [comment]
Hi,

You are right. I checked and in my OTU table taxa are columns
OTU Table:          [1891 taxa and 28 samples] 
and in the Tax Table the OTUs are in rows.

Could you tell me how I can change my OTU table ? I could not figure out how to use the phyloseq::taxa_are_rows() function properly.

Thank you so much for your help,
Camilla

**Comment by KasperSkytte** [comment]
Hi again. You just need to transpose with `t()`, but sometimes that can remove rownames and column names. Have you tried with just `phyloseq::otu_table(obj, taxa_are_rows = FALSE)@.Data` both places?

**Comment by camillaln** [comment]
Hi,
Yes I did try transposing but, as you said,  it did mess up the rowname and column names.
I also tried phyloseq::otu_table(obj, taxa_are_rows = FALSE)@.Data, but that didnt do it.

> otutable <- data.frame(OTU = rownames(phyloseq::otu_table(obj, taxa_are_rows = FALSE)@.Data), phyloseq::otu_table(obj, taxa_are_rows = FALSE)@.Data, phyloseq::tax_table(obj)@.Data,check.names = FALSE)
Error in data.frame(OTU = rownames(phyloseq::otu_table(obj, taxa_are_rows = FALSE)@.Data),  : 
  arguments imply differing number of rows: 28, 1891

I guess I have to try get the OUT name when I transpose my table.

Camilla

**Comment by camillaln** [comment]
Hi,
I got it working with a transposed otu table, and when I did it this time it kept the headers. (I am not sure what I did different last time when I didnt get it to work.)

Totu_table =t(otu_table(obj))
otu_table(obj)=Totu_table

Thanks for you help!

**Comment by KasperSkytte** [comment]
Great. Sorry for the late responses. Closing for now.

**Comment by Taimoor059** [comment]
Hi, 
my script
phyloseq::otu_table((green_otus, taxa_are_rows = FALSE), sample_data(green_samples), tax_table(taxas))

then
 Error: unexpected ',' in "phyloseq::otu_table((green_otus,"

**Comment by KasperSkytte** [comment]
@Taimoor059 that's a syntax error
