### ISSUE TITLE
amp_subset_taxa to have an option to remove singletons

### ISSUE THREAD

**Issue by Kirk3gaard** [KasperSkytte/ampvis2#61]
It would be nice if amp_subset_taxa would support removing OTUs with only 1 read across all samples. e.g. amp_subset_taxa(data,remove_singletons=T)

**Comment by KasperSkytte** [comment]
I think this makes more sense to do in `amp_load()` as a first step, since any singletons after a potential subset is not a 'true' singleton. Furthermore, it's impossible to identify singletons if the data has been normalised previously by `amp_subset_tax()` or `amp_subset_samples()`.

**Comment by KasperSkytte** [comment]
Fixed in https://github.com/MadsAlbertsen/ampvis2/commit/ab79861a495bb2867bc3372b5f3a07e7fcbac7b8
