### ISSUE TITLE
time_variable in amp_timeseries

### ISSUE THREAD

**Issue by afmbafmb** [KasperSkytte/ampvis2#64]
Hi! 

I am trying to plot read abundance data using amp_timeseries. The data came out nicely but I am just wondering if there is a way to change the x-axis to Day 0, 1, 2, 3, etc. instead of the as_date format in time_variable. 

Thanks for your time...

**Comment by KasperSkytte** [comment]
Hi there!

As ampvis2 uses `ggplot2` to generate plots, you can always adjust the layout etc to suit your needs. Have a look at https://ggplot2.tidyverse.org/reference/scale_date.html

**Comment by KasperSkytte** [comment]
In the examples I mean. Try something like `plot + scale_x_date(date_breaks = "1 day", date_labels = "Day %d")`

**Comment by afmbafmb** [comment]
Hi Kasper,

Thanks for your prompt reply. I tried your suggestion but it plots the x-axis by restarting the Days to 0 for each month (i.e. 2018/02/01 = Day 0, 2018/02/28 = Day 28 , 2018/03/28 = Day 28). 
Is there any workaround so that I can get continuous Days (i.e. 2018/02/01 to be shown as Day 0 and 2018/03/28 as Day 56 ). 
Sorry for troubling you with this. I am a novice.

**Comment by KasperSkytte** [comment]
Hi again

Something like this would do, assuming your dates are evenly spaced with 1 day, if not then you have to manually provide a vector to the `labels` argument.

``` r
library(ampvis2)
#> Loading required package: ggplot2
d <- amp_subset_samples(AalborgWWTPs, Year %in% 2014 & Plant %in% "Aalborg West")
#> 63 samples and 5994 OTUs have been filtered 
#> Before: 67 samples and 9430 OTUs
#> After: 4 samples and 3436 OTUs
uniqueDates <- sort(unique(as.Date(d$metadata$Date)))
amp_timeseries(d, 
               time_variable = "Date",
               split= TRUE,
               scales = "free_y") +
  scale_x_date(breaks = uniqueDates,
               labels = paste("Day", 1:length(uniqueDates)))
```

![](https://i.imgur.com/CzfeedA.png)

<sup>Created on 2019-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by afmbafmb** [comment]
Hi Kasper,

It worked! Thank you very much for the help...
