### ISSUE TITLE
Issues with hclustering 

### ISSUE THREAD

**Issue by shimingtan** [KasperSkytte/ampvis2#67]
Dear developers of Ampvis2,

I am trying to perform some hierarchical clustering with the "order_x_by" and "order_y_by" options, but I was not successful. 

These were the steps that I did:

```
# Calculate the Bray-Curtis dissimilarity matrix just for MTB community

data.dist.MTB <- vegdist(t(MTB_ampvis_RA$abund), method = "bray")
row.clus.MTB <- hclust(data.dist.MTB, method = "average")

```
```
# Ampvis heatmap
amp_heatmap(MTB_ampvis_RA, tax_aggregate = "Genus", tax_add = "Phylum",
            normalise = T, tax_show = 30, plot_values = F, 
          color_vector = c("white", "blue", "darkred"), plot_colorscale = "log10",
plot_legendbreaks = c(1, 5, 10),
order_x_by = row.clus.MTB)
```

My plot became a single column instead. Did I do something wrong here?

**Comment by KasperSkytte** [comment]
Hi

You don't have to do all that, just set `amp_heatmap(..., order_y_by = "cluster")` as described in the help-page (https://madsalbertsen.github.io/ampvis2/reference/amp_heatmap.html)

**Comment by shimingtan** [comment]
Hello there,


Will it be possible to include a dendrogram with the clustering in heatmap?


Thank you!


Best regards
Shi Ming

Research Fellow | Singapore Centre for Environmental Life Sciences & Engineering | Nanyang Technological University
T: +65-91402277 | shimingt@ntu.edu.sg
________________________________

**Comment by KasperSkytte** [comment]
Hi Shi Ming

Unfortunately not at the moment. But it's on the to-do list, I will see when I have time for it.

**Comment by shimingtan** [comment]
Dear Kasper,


Thanks for the reply!


I was looking at the "Venn Diagram" of Ampvis2 as well, but I had difficulty understanding the option for cut_a and cut_f. Will you be able to provide an example?


Thank you.


Best regards
Shi Ming

Research Fellow | Singapore Centre for Environmental Life Sciences & Engineering | Nanyang Technological University
T: +65-91402277 | shimingt@ntu.edu.sg
________________________________

**Comment by shimingtan** [comment]
Dear Kasper,


Will it be possible to modify the themes of the amp_boxplot function?


I tried modifying it but a "NULL" response came back.


E.g.


> a <- amp_boxplot(MTB_ampvis_merged, tax_show = 30, tax_add = "Phylum", normalise = F,
+             plot_log = T, sort_by = "mean", plot_type = "boxplot", tax_empty = "best",
+             detailed_output = T)
>
> a + scale_y_continuous(name = "Mean ozone in parts per billion")
NULL


Thank you.


Best regards
Shi Ming

Research Fellow | Singapore Centre for Environmental Life Sciences & Engineering | Nanyang Technological University
T: +65-91402277 | shimingt@ntu.edu.sg
________________________________

**Comment by KasperSkytte** [comment]
Hi again

Regarding `amp_venn()`: The names of `cut_a` and `cut_f` are perhaps not intuitive, I admit. But they are thresholds for defining when a OTU should be considered a "core" OTU. `cut_a` is the minimum abundance for being considered, `cut_f` is the minimum frequency above the `cut_a` threshold for being considered a "core" OTU. 

Regarding `amp_boxplot()`: When setting `detailed_output = TRUE` the function returns a list, not a `ggplot2` object. The plot is then inside the list as `a$plot`.

**Comment by shimingtan** [comment]
Dear Kasper,

Thanks for your explanation! Does Ampvis2 have a function that prunes singletons that are not present in at least one sample?

Best regards
Shi Ming

Research Fellow | Singapore Centre for Environmental Life Sciences & Engineering | Nanyang Technological University
T: +65-91402277 | shimingt@ntu.edu.sg
________________________________

**Comment by Kirk3gaard** [comment]
Hi Shi Ming 

See https://github.com/MadsAlbertsen/ampvis2/issues/61. Please start a new issue for new problems to keep the "chat function" easier to make into tasks :D

Best regards
Rasmus

**Comment by KasperSkytte** [comment]
Hi again. Yes, it may be easier with e-mails, but nice to keep things separate for when other people search. I added a `pruneSingletons` argument to `amp_load()` now (https://github.com/MadsAlbertsen/ampvis2/commit/ab79861a495bb2867bc3372b5f3a07e7fcbac7b8), so they are removed initially when loading the data if set to `TRUE`.

**Comment by dsgregoire** [comment]
Hello Kasper,

I have also been trying to add dendograms to by ampvis heatmaps and I had some questions. I see that you mentioned you were planning on adding this functionality into the package and was curious if you had a chance to do so. Furthermore, I am wondering what type of clustering method is being employed. If I know that, I may be able to reverse engineer it using hclust so that I know what type of dendogram I should be working towards. If you could please let me know that would be much appreciated.

Best regards,

Daniel

**Comment by KasperSkytte** [comment]
Hi Daniel

I won't have time before next year to give it a go. It will most likely be similar to this https://jcoliver.github.io/learn-r/008-ggplot-dendrograms-and-heatmaps.html using ggdendro. In the meantime you are welcome to give it a go and make a pull request.
