### ISSUE TITLE
Facet_by, order_x_by don't work together in amp_heatmap

### ISSUE THREAD

**Issue by Lulbilule** [KasperSkytte/ampvis2#71]
Hi, 

I am trying to organise my heatmap in the right order but I'm struggling as some of the arguments don't work together. 

First, I would like to order x as 'snow', 'soil', 'FT'. If I use facet_by, it doesn't work anymore. 
Also, I would like to order the facet as: D-109, D0, D5, D9, D14, D20, D29 but I'm not sure how. 

Any help would be great. 
![heatmap_github](https://user-images.githubusercontent.com/53977511/62824524-62968c00-bb97-11e9-988c-df110c5ef5a8.png)

Thanks in advance,
Lucie

**Comment by KasperSkytte** [comment]
Hi Lucie

Sorry for the late response. It's currently not possible with `order_x_by` alone, but setting factor levels in the metadata before using `amp_heatmap()` will solve it, like below. You can provide a vector manually to the `levels` argument of `factor()` or if you have many values in the group or facet columns you can just extract the unique values and set the order with a numeric vector as below:

``` r
library(ampvis2)
#> Loading required package: ggplot2
d <- amp_subset_samples(AalborgWWTPs, Year %in% c("2014", "2015"))
#> 51 samples and 2965 OTUs have been filtered 
#> Before: 67 samples and 9430 OTUs
#> After: 16 samples and 6465 OTUs

# unordered
amp_heatmap(
  d,
  group_by = "Plant",
  facet_by = "Year"
)
```

![](https://i.imgur.com/LFfbhJI.png)

``` r
#ordered
d$metadata$Plant <- factor(d$metadata$Plant, levels = unique(d$metadata$Plant)[c(2,1)])
d$metadata$Year <- factor(d$metadata$Year, levels = unique(d$metadata$Year)[c(2,1)])
amp_heatmap(
  d,
  group_by = "Plant",
  facet_by = "Year"
)
```

![](https://i.imgur.com/o77E4WM.png)

<sup>Created on 2019-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
