### ISSUE TITLE
Dear Kasper, I have plotted an nmds and looking for p-values that shows the cofidence in distribution of objects in the plot. Also p-values for significant environmental variables (envfit in vegan). Now I have nmds object ( a list of nine) with nmds$data showing only the caldulated distances NMDS1 and NMDS2, but no p-values. Any suggestions where to look for or how to calculate p-values in ampvis2? Thanks much

### ISSUE THREAD

**Issue by zahidrehman** [KasperSkytte/ampvis2#73]
Thank you for using ampvis2!

If you encounter a problem with ampvis2 that you are unable to resolve, this is the place for discussing the problem with developers to find a solution. To best help you quickly, please first make sure that:

 - you have the latest version of the package installed
 - you have carefully read the [documentation](https://madsalbertsen.github.io/ampvis2/reference/index.html) of the ampvis2 function(s) used
 - you have searched the GitHub issues page or the internet for similar or identical problems

Should the problem still persist, then please provide a *minimal* reproducible example, preferably using [reprex](https://www.tidyverse.org/help/#reprex), with self-contained code so that anyone can copy the code and reproduce the problem to easily start debugging without further communication. 

If you suspect that the data used is involved in causing the trouble, then please upload it (preferably a minimal subset) to [figshare](https://figshare.com/) or similar services and provide a link to it.

**Comment by KasperSkytte** [comment]
Hi there

`amp_ordinate()` by default returns a ggplot2 plot object, which is a list. If you set `detailed_output = TRUE` you should get a list of 8 with multiple different elements, one of them is the `evf_factor_model` or `evf_numeric_model`, which is the result of vegans envfit.

**Comment by zahidrehman** [comment]
Hi Kasper, I tried detailed_output = TRUE, I indeed get list of 8 but values for both evf_factor_model and evf_numeric_model are NULL.

**Comment by KasperSkytte** [comment]
Hi again. Then you also need to set `envfit_factor` or `envfit_numeric` to a metadata variable. See https://madsalbertsen.github.io/ampvis2/reference/amp_ordinate.html
