### ISSUE TITLE
Does ampvis2 exports an object in biom format?

### ISSUE THREAD

**Issue by FilipeMatteoli** [KasperSkytte/ampvis2#74]
I am trying to export a biom file, tailored in phyloseq, but I would like to keep it in this format.

I was able to convert my phyloseq following [this](https://madsalbertsen.github.io/ampvis2/articles/faq.html#loading-phyloseq-objects), then i exported it as a csv otu_table.
Unfortunately, this leaves all metadata out of the exported file. Maybe I am missing something or this has not been implemented yet?

Best,

**Comment by KasperSkytte** [comment]
Hi there

Currently you can only import and convert to ampvis2 format, not the other way around. You cannot export in biom format unless you convert back to phyloseq and export through there. But if this is needed by many I can maybe implement it. But if you load the data using phyloseq, you can just export through it too without going through ampvis2? If you just do regular filtering, it's easily done in phyloseq as well. But if you want to try, you can just load as `phyloseq` object by passing the elements in the ampvis2 object, eg `data$abund` for counts, `data$tax` for taxonomy, `data$metadata` for sample data etc.
