### ISSUE TITLE
Venn diagram of core OTUs

### ISSUE THREAD

**Issue by apoosakkannu** [KasperSkytte/ampvis2#75]
Hi, I am trying to use ampvis2 (latest package) to plot venn diagram of core OTUs in my samples. But i am getting an following error, 
The code is 
```
amp_venn(
  ampvis2_physeq_clean_triatomine_nest_rarefy, 
  group_by = "T_cruzi", 
  cut_a = 0.1, 
  cut_f = 80,
  text_size = 5,
  normalise = TRUE, 
  detailed_output = FALSE
)
```

The error is "Factor `OTU` contains implicit NA, consider using `forcats::fct_explicit_na"

Could you give me solution to overcome this problem?

**Comment by KasperSkytte** [comment]
Hi there...

There are `NA`'s in the taxonomy. You need to have a look at these and remove them in both `$abund` and `$tax` before continuing with anything.
