### ISSUE TITLE
Alpha diversity without singletons

### ISSUE THREAD

**Issue by GenomicaMicrob** [KasperSkytte/ampvis2#76]
Hi, excellent package! I would like that when you run the amp_alphadiv function without singletons, it gives you a figure and not only send you a warning and drops.

**Comment by KasperSkytte** [comment]
Hi there...

Can you please provide a minimal reproducible example of exactly what you have run, tried, and desired output etc. The function gives a warning if there are no singletons, but continues anyways.

**Comment by GenomicaMicrob** [comment]
Yes indeed it does the analysis, but maybe I was expecting a nice graph of the results, maybe a violin plot grouping by a metadata value?

**Comment by KasperSkytte** [comment]
The documentation says it returns a data frame. So there is no issue here, closing.
