### ISSUE TITLE
Installation problem (solved) on R 3.6.1 (Windows) caused by ggplot2

### ISSUE THREAD

**Issue by jgrzadziel** [KasperSkytte/ampvis2#77]
I just want to report an issue during the installation of ampvis2 package on:
> Windows 10 x64
> R 3.6.1

The problem is ggplot2 package.
To resolve it I had to install ggplot2 via:
>devtools::install_github("tidyverse/ggplot2")

instead of:

>install.packages("ggplot2") or install.packages("tidyverse")

I don't know why, since the version of ggplot2 is the same from both sources.

**Comment by KasperSkytte** [comment]
Hi there. `ggplot2` should be installed automatically with `ampvis2` without manually doing it. But what was the error message when it failed?

**Comment by jgrzadziel** [comment]
@KasperSkytte 

 ```
Installing package into ‘C:/Users/user/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ampvis2' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR:  package 'ggplot2' was built under R version 3.6.1
ERROR: lazy loading failed for package 'ampvis2'
* removing 'C:/Users/user/Documents/R/win-library/3.6/ampvis2'
Error: Failed to install 'ampvis2' from GitHub:
  (converted from warning) installation of package ‘C:/Users/user~1/AppData/Local/Temp/RtmpMJi7FA/file1828d83e0551ae/ampvis2_2.5.1.tar.gz’ had non-zero exit status
```

**Comment by KasperSkytte** [comment]
I think this is because you installed `ggplot2` previously on a newer version of R than the current one you are using.

**Comment by jgrzadziel** [comment]
Thank you, 
if that is the case the issue can be closed.
I'm sorry for the confusion.
