### ISSUE TITLE
Problem with amp_ordinate NMDS

### ISSUE THREAD

**Issue by vbalanus** [KasperSkytte/ampvis2#78]
Dear Developer,
 I tried to create an NMDS-plot for my dataset.
 I've run the following code:
`amp_ordinate(AalborgWWTPs,
             type = "NMDS",distmeasure = "bray",
             transform = "none")`
With the AalborgWWTPs dataset I have no problem, and I've got the NMDS-plot.
![AalborgWWTPs_NMDS](https://user-images.githubusercontent.com/56400873/66578691-d6dfb280-eb7b-11e9-8b2b-ae48a8e5ee5b.png)
But when I used my own dataset with the following OTU-table: 
[BF Toxin 2018 Ampvis Bact OTU.txt](https://github.com/MadsAlbertsen/ampvis2/files/3713118/BF.Toxin.2018.Ampvis.Bact.OTU.txt) I've got the following error-message:
`# Warning message:
In vegan::metaMDS(inputmatrix, trace = FALSE, ...) :
  stress is (nearly) zero: you may have insufficient data`
and this ordination:
![BF_toxin_NMDS](https://user-images.githubusercontent.com/56400873/66579186-b532fb00-eb7c-11e9-9c5f-d05367465167.png)

I've checked `metaMDS` in vegan package, and I could create correct ordination for AalborgWWTPs dataset and not useable for my BF toxin dataset.
I've compared the two dataset, and I couldn't find any relevant differences. If I used the  [Past program](http://folk.uio.no/ohammer/past/) it could create NMDS ordination from both dataset.
 Any suggestions, what can be the problem?
 Thanks is advance!

**Comment by vbalanus** [comment]
Meanwhile I've find the solution, but I do not really understand the situation:
2 of my samples are far away from the others if using Bray-Curtis distances for NMDS. If I omit that samples, I get the correct ordination. If using Euclidean distances, there is no problem.
But still, if I use [Past program](http://folk.uio.no/ohammer/past/) it could create NMDS ordination with Bray-Curtis distances for the whole dataset.
Do others have similar experiences?

**Comment by KasperSkytte** [comment]
Hi there

When you have a few samples that are just very different from every other sample, their distances will just dominate the first axis. The result is not incorrect. Even when just inspecting the abundance table manually, it's clear that `TTF0D` and `TTF0R` are just very different. But I don't know about the Past software, so I cannot say why it creates different results. There are different implementations of the nMDS algorithm, maybe it prefilters or applies some transformation, I don't know. But euclidean distance is very different from Bray-Curtis or others, and it's generally not suited for community data without transformation.
