### ISSUE TITLE
Issue with species_plotly function in amp_ordinate

### ISSUE THREAD

**Issue by moverg** [KasperSkytte/ampvis2#80]
Hi,
We have encountered a bug in the `species_plotly` function in `amp_ordinate`.
The species description in the box when you hover over a species with the mouse does not match the label given by the `species_nlables` function in the following code:
`amp_ordinate(data = AalborgWWTPs, 
             type = "PCA", 
             transform = "hellinger",
             sample_color_by = "Plant",
             sample_colorframe = T,
            species_plot = T,
             species_nlabels = 5,
             species_plotly = T)`
Will you please take a look at it?
Thanks,

**Comment by KasperSkytte** [comment]
Hi

Thanks for noticing. I have made a fix for it, unfortunately the plotly labels had the wrong order.

**Comment by KasperSkytte** [comment]
Fixed in 0c2cf38b340200894d8e560ed1cccee9c783234b
