### ISSUE TITLE
normalizing across samples using a variance stabilizing transformation (vst) 

### ISSUE THREAD

**Issue by slambrechts** [KasperSkytte/ampvis2#83]
Hello,

your [https://madsalbertsen.github.io/ampvis2/reference/amp_subset_samples.html](url) documentation led me to the interesting paper by McMurdie and Holmes where they show that a good method of normalizing across samples is to use a variance stabilizing transformation (as is implemented in the DESeq2 package). I was wondering if you have any plans on adding this to `amp_subset_samples`? 

Best,

Sam

McMurdie, P.J. & Holmes, S. (2014). Waste not, want not: Why rarefying microbiome data is inadmissible. PLoS Comput Biol 10(4): e1003531. DOI:10.1371/journal.pcbi.1003531

**Comment by KasperSkytte** [comment]
Hi there

Happy new year, finally back from 2 weeks of holidays. But no, we don't have any plans doing that. I think that would be double work, as it's already implemented in phyloseq. But you can easily load your data with `phyloseq` and convert to `ampvis2` format as described [here](https://madsalbertsen.github.io/ampvis2/articles/faq.html#loading-phyloseq-objects).
