### ISSUE TITLE
amp_heatmap (tax_class) feature request

### ISSUE THREAD

**Issue by slambrechts** [KasperSkytte/ampvis2#84]
Hello,

First of all, thank you for the wonderful visualisation tool! If I understand correctly it is not possible to specify more then 1 phyla to be converted to class level when using the `tax_class` argument in `amp_heatmap`? I would like to convert 2 or 3 phyla as class levels instead of just 1, but when trying this does not seem to be possible?

Best,

Sam

**Comment by KasperSkytte** [comment]
Hi there

Happy new year, finally back from 2 weeks of holidays. Can you please provide a minimal reproducible example of your issue? As you can see below, I have no problems doing just that.

``` r
library(ampvis2)
#> Loading required package: ggplot2

#tax_class = NULL (default)
amp_heatmap(
  AalborgWWTPs,
  group_by = "Plant",
  tax_aggregate = c("Phylum", "Class"))
```

![](https://i.imgur.com/lzLjEy1.png)

``` r

#tax_class with one phylum
amp_heatmap(
  AalborgWWTPs,
  group_by = "Plant",
  tax_aggregate = c("Phylum", "Class"), 
  tax_class = "p__Proteobacteria")
```

![](https://i.imgur.com/CcyjFVc.png)

``` r

#tax_class with two phyla
amp_heatmap(
  AalborgWWTPs,
  group_by = "Plant",
  tax_aggregate = c("Phylum", "Class"), 
  tax_class = c("p__Proteobacteria", "p__Firmicutes"))
```

![](https://i.imgur.com/9j8IB4j.png)

<sup>Created on 2020-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
