### ISSUE TITLE
Error in unit(rep(just$hjust, n), "npc")

### ISSUE THREAD

**Issue by susheelbhanu** [KasperSkytte/ampvis2#85]
Hi, 
Thanks a lot for the great tool. I'm running into the below issue when I try to run my own data. 
```
Error in unit(rep(just$hjust, n), "npc") : 
  'x' and 'units' must have length > 0
In addition: Warning messages:
1: The data has already been normalised. Setting normalise = TRUE (the default) will normalise the data again and the relative abundance information about the original data of which the provided data is a subset will be lost. 
2: Transformation introduced infinite values in discrete y-axis 
```

I've loaded and tried to run the package as shown here:
```

[all_new_motus_V3_V4_V5_V6.txt](https://github.com/MadsAlbertsen/ampvis2/files/4182591/all_new_motus_V3_V4_V5_V6.txt)
[all_new_COSMIC_metadata.txt](https://github.com/MadsAlbertsen/ampvis2/files/4182594/all_new_COSMIC_metadata.txt)
install.packages("remotes")
remotes::install_github("MadsAlbertsen/ampvis2")
library(ampvis2)

# example data
myotutable <- read.csv("all_new_motus_V3_V4_V5_V6.csv", check.names = FALSE)
mymetadata <- read.csv("all_new_COSMIC_metadata.csv", check.names = FALSE)

d <- amp_load(otutable = myotutable,  metadata = mymetadata)

#basic heatmap
amp_heatmap(d, group_by = "group", 
            tax_aggregate = "Genus",
            tax_show = 25,
            facet_by = "timepoint", 
            plot_values_size = 3,
            color_vector = c("white", "darkred")) +
  theme(axis.text.x = element_text(angle = 0, size=10),
        axis.text.y = element_text(size=10),
        legend.position="right") +
theme(strip.background = element_rect(colour = "black", fill = "white"), 
      strip.text = element_text(size=10, family="Helvetica"))
```

I've attached the files here. Please let me know if you need any other information, and thanks again for your help!

Best,
Susheel 

[all_new_motus_V3_V4_V5_V6.txt](https://github.com/MadsAlbertsen/ampvis2/files/4182597/all_new_motus_V3_V4_V5_V6.txt)
[all_new_COSMIC_metadata.txt](https://github.com/MadsAlbertsen/ampvis2/files/4182599/all_new_COSMIC_metadata.txt)

**Comment by KasperSkytte** [comment]
Hi susheel. I may not respond before late March since I am on paternity leave, sorry for the inconvenience.

**Comment by susheelbhanu** [comment]
No worries @KasperSkytte. Congratulations and wish you the best!

**Comment by KasperSkytte** [comment]
Hi again

I tried your code and `amp_load` returns the error `Error: Cannot find OTU ID's. Make sure they are provided as rownames or in a column called "OTU".`. If I inspect the data it seems both files are loaded incorrectly and returns a data.frame with just one column. The separator should have been set to `"\t"` . Are you sure you ran it exactly as you wrote here since you didn't get that error?
I recommend reading flat text files as data.frames using `data.table::fread()` as it autodetects separator and guesses variable types, and it's extremely fast! Your code (the ampvis2 part) works fine otherwise:

``` r
library(ampvis2)
#> Loading required package: ggplot2

# example data
myotutable <- data.table::fread("https://github.com/MadsAlbertsen/ampvis2/files/4182591/all_new_motus_V3_V4_V5_V6.txt")
mymetadata <- data.table::fread("https://github.com/MadsAlbertsen/ampvis2/files/4182594/all_new_COSMIC_metadata.txt")

d <- amp_load(otutable = myotutable,  metadata = mymetadata)

#basic heatmap
amp_heatmap(d, group_by = "group", 
            tax_aggregate = "Genus",
            tax_show = 25,
            facet_by = "timepoint", 
            plot_values_size = 3,
            color_vector = c("white", "darkred")) +
  theme(axis.text.x = element_text(angle = 0, size=10),
        axis.text.y = element_text(size=10),
        legend.position="right") +
  theme(strip.background = element_rect(colour = "black", fill = "white"), 
        strip.text = element_text(size=10, family="Helvetica"))
#> Warning: The data has already been normalised. Setting normalise = TRUE (the
#> default) will normalise the data again and the relative abundance information
#> about the original data of which the provided data is a subset will be lost.
#> Warning: Transformation introduced infinite values in discrete y-axis
```

![](https://i.imgur.com/GU0rekM.png)

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by susheelbhanu** [comment]
@KasperSkytte Thank you very much for the pointers with the `data.table::fread`. For some reason, I got the same error, but then removed all the installed R packages, and re-installed `ampvis2` from this repository, all over again. That seemed to have done the trick. 

Thanks again for your help with this! Cheers..
