### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by mikemc** [KasperSkytte/ampvis2#86]
The link to the heatmap blogpost in the README gives a "Page not found" error. Offending line:

https://github.com/MadsAlbertsen/ampvis2/blob/e008ee100bcb9a2ada97b7f120ad7218a782167d/README.Rmd#L21

**Comment by KasperSkytte** [comment]
Thank you for the notification. I have no idea why wordpress suddenly regenerated a new link for it. Fixed.
