### ISSUE TITLE
facet_by error in 'amp_heatmap' function 

### ISSUE THREAD

**Issue by Jessie-HOU** [KasperSkytte/ampvis2#88]
Thank you for using ampvis2!

If you encounter a problem with ampvis2 that you are unable to resolve, this is the place for discussing the problem with developers to find a solution. To best help you quickly, please first make sure that:

 - you have the latest version of the package installed
 - you have carefully read the [documentation](https://madsalbertsen.github.io/ampvis2/reference/index.html) of the ampvis2 function(s) used
 - you have searched the GitHub issues page or the internet for similar or identical problems

Should the problem still persist, then please provide a *minimal* reproducible example, preferably using [reprex](https://www.tidyverse.org/help/#reprex), with self-contained code so that anyone can copy the code and reproduce the problem to easily start debugging without further communication. 

If you suspect that the data used is involved in causing the trouble, then please upload it (preferably a minimal subset) to [figshare](https://figshare.com/) or similar services and provide a link to it.

**Comment by Jessie-HOU** [comment]
Hello,

I am trying to using amp_heatmap function to draw heatmap for 16S data. But the facet_by parameter gave the following error. I have searched google and tried, but have not fixed this issue yet. 

> amp_heatmap(d,group_by = "Time_point",
+             facet_by = "Group",
+             tax_aggregate = "Genus",
+             tax_show = 25)
Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

Any help or suggestion will be appreciated. Thanks in advance!

Best regards,
Jessie

**Comment by Jessie-HOU** [comment]
Hi there!

I have find the solution to this error. That is, I changed the column name "Group" to "Subject_type". It does works! It seems that "Group" cannot be used as column names (Is it the 'key words' of this ampvis2 package?) when calling the amp_heatmap function. I am not sure about this currently, though.

Best regards,
Jessie

**Comment by KasperSkytte** [comment]
Hi Jessie.

Yes it could be that the variable name `Group` can cause some trouble. But simply rename it and it should work fine.

**Comment by Jessie-HOU** [comment]
Dear Kasper Skytte,

I see. Thank you for your information!

Best regards,
Jessie
