### ISSUE TITLE
amp_venn issue

### ISSUE THREAD

**Issue by lesserof2weevils** [KasperSkytte/ampvis2#91]
Hi, I'm having an issue creating a Venn diagram of my shared OTUs between three host species. I have imported my data from a phyloseq object, and then running: 
amp_venn(ampvis2_F, group_by = 'Species', normalise = FALSE)

The error returned is:
Error: `i` must have one dimension, not 2.

Any help is greatly appreciated
Thanks, 
James

**Comment by KasperSkytte** [comment]
Hi James

I think this is a data specific issue. Can you provide a subset of your data so I can test?

**Comment by lesserof2weevils** [comment]
Hi Kasper,

Thanks for the reply. The error seems to be resolved when I reran everything this morning. I am having an NA issue, which needs to be resolved with forecast::fct_explicit_na. Quick question, can I run this function on my $tax in the ampvis2 object?

Many thanks, 
James

**Comment by KasperSkytte** [comment]
Hi again

Good. I would need data and exact commands to reproduce to test, but I guess that shouldn't cause any harm.

**Comment by lesserof2weevils** [comment]
I've resolved this issue and found a work around for the NAs.

Thanks, 
James

**Comment by KasperSkytte** [comment]
Okay great. Please share the solution so others can benefit from it. Was it just using explicit `NA`s?

**Comment by lesserof2weevils** [comment]
I found a great work around by shifting the taxonomy table into a temp object, and using dplyr mutating the blank cells, putting in NAs, and then making them explicit. I found that if you do this, they're converted into factors, so make them characters again and put back into the amp_obj$tax

`temp <- Fambpvis$tax
temp <- temp %>% mutate_all(na_if, "") %>% 
  mutate_if(is.character,
            fct_explicit_na,
            na_level = '(missing)') %>%
  mutate_if(is.factor,
            as.character)
Fambpvis$tax <- temp`

**Comment by lixiaopi1985** [comment]
I recently encountered the sample problem. Not because the NAs problem mentioned in the previous discussion. I debugged the source code and found out the issue was from subsetting tibble. i.e. tibble[, 2] does not return a one dimensional vector instead it maintains tibble structure. So to get the subset, use tibble[[2]] or convert the logical operators into a vector:

` if (ncol(a) == 4) {

                c_ABC <- subset(a, as.vector(a[, 2] == 1 & a[, 3] == 1 & a[, 4] == 1))  
                c_AB <- subset(a, as.vector(a[, 2] == 1 & a[, 3] == 1 & a[, 4] == 0))
                c_AC <- subset(a, as.vector(a[, 2] == 1 & a[, 3] == 0 & a[, 4] == 1))
                c_BC <- subset(a, as.vector(a[, 2] == 0 & a[, 3] == 1 & a[, 4] == 1))
                c_A <- subset(a, as.vector(a[, 2] == 1 & a[, 3] == 0 & a[, 4] == 0))
                c_B <- subset(a, as.vector(a[, 2] == 0 & a[, 3] == 1 & a[, 4] == 0))
                c_C <- subset(a, as.vector(a[, 2] == 0 & a[, 3] == 0 & a[, 4] == 1))
                c_n <- subset(a, as.vector(a[, 2] == 0 & a[, 3] == 0 & a[, 4] == 0))
}` 

And that solved the problem.

Hope it can draw your attention.
