### ISSUE TITLE
ampvis2 shiny 

### ISSUE THREAD

**Issue by miguensblanco** [KasperSkytte/ampvis2#96]
Hi Mad,

First of all, thanks for ampvis2 and the other tools that you have developed. Quick question, is the shiny app still available? When I am uploading the metadata to give it a go I keep getting the message _Error: An error has occurred. Check your logs or contact the app author for clarification_  I never can pass that. I'd appreciate any help!

Best,

Jesus

**Comment by KasperSkytte** [comment]
Hi there

Yes it's available or else you couldn't enter at all. But I would need to get a hold of your data or a subset thereof to debug. It's hard to know from the logs which session was you.

**Comment by miguensblanco** [comment]
Hi again, thanks for the quick reply. 

 I attach the metadata file that I was trying to upload.
[MI-PART_Metadata_ampvis.txt](https://github.com/MadsAlbertsen/ampvis2/files/4858587/MI-PART_Metadata_ampvis.txt)

I thought that I would need to fight more around with the OTU table since my one is not made through Qiime2 but DADA2 but let's see if I can manage to get it done. Thanks!!

Jesus

**Comment by KasperSkytte** [comment]
Not easy for you to know, but the error when loading metadata is: `File is encoded in UTF-16, this encoding is not supported by fread(). Please recode the file to UTF-8.`. Maybe also check the encoding of OTU table too

**Comment by KasperSkytte** [comment]
`Latin-1` or `UTF-8` are the only ones supported

**Comment by miguensblanco** [comment]
Weird, I have been trying multiple times with my file, I ended up trying with the example metadata and I got the same problem
[metadata.txt](https://github.com/MadsAlbertsen/ampvis2/files/4863990/metadata.txt) 

I think I have recode it all the files I tried but I may have done something wrong.

Cheers

**Comment by KasperSkytte** [comment]
Okay, does that mean you got it to work?

**Comment by miguensblanco** [comment]
No, no, I got the same problem. I have downloaded the minimal example metadata and without modify nothing about it, just try to upload it as my own metadata and it doesnt work, it gives me the same issue with every file I have tried.

I may try with using the code.

**Comment by KasperSkytte** [comment]
Okay. If you upload unmatching OTU table and metadata, it will also fail. Can you send me the OTU table or subset thereof so I can test what's wrong? Did you try saving with UTF-8 before uploading?

**Comment by miguensblanco** [comment]
I really appreciate your help. I attach the two files I have try for the metadata (both UTF-8) and the biom file.

[AmpVis2.zip](https://github.com/MadsAlbertsen/ampvis2/files/4881306/AmpVis2.zip)

Cheers

**Comment by KasperSkytte** [comment]
Arh I see now. It's because ampvis2 currently only supports BIOM format version >2.0, and your file is in the older 1.0 format. Sample metadata is fine. You can try running the app from RStudio on your local machine with (described [here](https://github.com/KasperSkytte/Amplicon-visualiser#amplicon-visualiser)) to see the exact errors if you should get more.
If you can convert the BIOM file to version 2.0 or later it should work. But I will try updating `amp_import_biom()` to try to detect the BIOM format version and maybe react differently with different BIOM versions.
