### ISSUE TITLE
amp_ordinate nMDS + weighted unifrac

### ISSUE THREAD

**Issue by AviHuene** [KasperSkytte/ampvis2#98]
Hello Kasper,

I wanted to ask why the nMDS ordination with a weighted or unweighted unifrac was removed from the amp_ordinate function.

Thank you,
Avril

**Comment by KasperSkytte** [comment]
Hi there. I guess that's a mistake, I can't recall why it was removed. I will add it again once back from holidays and paternity leave (mid august). For now you can just install an older ampvis2 version.
