### ISSUE TITLE
amp_boxplots by OTUs?

### ISSUE THREAD

**Issue by jarrodscott** [KasperSkytte/ampvis2#99]
Hi there.

Is it possible to use `amp_boxplots` to display OTUs rather than aggregating by taxa?  I have a low diversity data set with poor classification at lower ranks (i.e., Genus, species) so I would just like to display box plots for top OTUs. I have tried tweaking the various parameters but no matter what I do, I get back a plot with---for some reason---only really rare OTUs. 

Maybe it doesn't make sense to display info in this way since we get similar outputs with `amp_heatmap` but I would like to compare the heatmap and boxplots. Thanks!

**Comment by KasperSkytte** [comment]
Hi

Have you set `tax_aggregate = "OTU"`? Keep in mind boxplots are sorted by median and heatmap by mean (though median probably makes more sense even for the heatmap, community data are rarely normally distributed)

**Comment by jarrodscott** [comment]
Hi @KasperSkytte 

I did set `tax_aggregate = "OTU"` but the median v. mean was the issue. Thank you for clarifying. Problem solved.

**Comment by KasperSkytte** [comment]
Great!
